cssm_connection: off
api_keys:
  client_id: <Your client_id obtained from apidocs-prod.cisco.com>
  client_secret: <Your client_secret obtained from apidocs-prod.cisco.com>

#  app_uuid: cisco123
  
devices:
#  -
#    id: 1
#    ip: 10.194.234.142
#    username: cisco
#    password: cisco
  -
    id: 2
    ip: 10.194.234.144
    username: test
    password: test
    
#    ip: 172.25.212.187
#    username: test
#    password: test

  
